import { Link } from 'react-router-dom';
import { endpoints } from '../../api/endpoints';
import { useResource } from '../../api/resources';
import { AsyncState } from '../common/AsyncState';
import { Counts, panelClass } from '../reviews/ReviewPresentation';
export function AnalyticsTab({ scope, installation, repo }: { scope: string; installation: number; repo: string }) {
  const state = useResource(`${scope}:trends`, s => endpoints.trends(installation, repo, s), () => 30_000);
  const data = state.data;
  return <div className="space-y-4"><button className="text-primary-400 underline" onClick={state.refresh}>Refresh analytics</button><AsyncState {...state} hasData={!!data} />{data && <>
    <div className="grid sm:grid-cols-3 gap-3">{[['Reviews', data.totals.reviews], ['Completed', data.totals.completed], ['Failed / skipped', `${data.totals.failed} / ${data.totals.skipped}`], ['Coverage recorded', data.totals.coverage_recorded_reviews], ['Coverage complete', data.totals.coverage_complete_reviews], ['Coverage gaps', data.totals.reviews_with_coverage_gap], ['Auto-fix attempts', data.totals.autofix.created], ['Approved', data.totals.autofix.approved], ['Rejected', data.totals.autofix.rejected]].map(([label, value]) => <div key={label} className={panelClass}><p className="text-xs text-neutral-400">{label}</p><p className="text-2xl font-mono">{value}</p></div>)}</div>
    <Counts counts={data.totals.severity_counts} /><p className="text-xs text-neutral-400">Latest {data.range.review_count} reviews in this range. Weighted index uses server weights: {Object.entries(data.totals.weights_used).map(([s, n]) => `${s}=${n}`).join(', ')}.</p>
    {!data.points.length ? <p>No review history yet.</p> : <><div className={panelClass}><h3 className="font-semibold">Weighted findings over time</h3><div className="flex items-end gap-1 h-32" role="img" aria-label="Weighted finding index, oldest to newest; exact values and coverage limitations follow in the table">{data.points.map(p => <div key={p.review_id} title={`Review ${p.review_id}: ${p.weighted_index}${p.coverage_complete ? '' : ' — incomplete coverage'}`} className={`flex-1 min-w-1 ${p.coverage_complete ? 'bg-primary-500' : 'bg-neutral-600 border border-dashed border-severity-medium'}`} style={{ height: `${Math.max(2, p.weighted_index / Math.max(1, ...data.points.map(q => q.weighted_index)) * 100)}%` }} />)}</div><p className="text-xs text-neutral-400">Gray points have incomplete or unknown coverage. Lower counts do not establish an improvement.</p></div>
    <div className="overflow-auto"><table className="w-full text-sm text-left"><thead><tr><th>Review</th><th>Status</th><th>Findings / index</th><th>Coverage</th></tr></thead><tbody>{data.points.map(p => <tr key={p.review_id} className="border-t border-neutral-800"><td className="py-3"><Link to={`/reviews/${p.review_id}`} className="text-primary-400">#{p.review_id} · PR #{p.pr_number}</Link><p className="text-xs text-neutral-500">{p.created_at ?? 'Date not recorded'}</p></td><td>{p.status}</td><td>{p.total_findings} / {p.weighted_index}</td><td>{p.coverage_complete ? 'Complete' : <>{p.degraded_agents.length > 0 && <p>Degraded/failed: {p.degraded_agents.join(', ')}</p>}{p.unrecorded_agents.length > 0 && <p>Unrecorded: {p.unrecorded_agents.join(', ')}</p>}{!p.degraded_agents.length && !p.unrecorded_agents.length && 'Incomplete'}</>}</td></tr>)}</tbody></table></div></>}
  </>}</div>;
}
